[package]
name = "my_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = "0.4.0" # gdext version - https://github.com/godot-rust/gdext/releases
rand = "0.9.2"
